#!/bin/bash

function update()
{
   sudo apt-get -y update
   sudo apt-get -y dist-upgrade
   sudo apt-get -y autoremove
   sudo apt-get -y autoclean
}

# Check for internet connection
ping -q www.google.com -c 1 &> /dev/null
RESULT=$?
if [ $RESULT != 0 ]; then
  zenity --text="Please connect to the Internet first" --info
  exit 1
fi

# Call the update function and capture the PID
update &
PID=$!

# progress dialog and give focus
(
for I in {0..99..2}; do
  sleep 2
  # Check if the Update process is still alive
  if ! ps -p $PID > /dev/null 2>&1; then
        # the update is ready
        echo "99"
        echo "#Ready"
        sleep 3
        break
  fi
  echo "$I"
done

echo "100"
) |
zenity --progress --no-cancel --text="Updating Kanux..." --width=300 --height=90 --auto-close --auto-kill

exit 0
