#!/usr/bin/env python
# post_update
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

import sys
from kano_updater.Utils import Update

update = Update(sys.argv[1], sys.argv[2])

if update.from('Kanux-Beta-1.0').to('Kanux-Beta-1.0.1'):
    pass
