#!/usr/bin/env python
# post_update
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

from kano_updater.Utils import *

old_ver = OSVersion.from_version_string(sys.argv[1])
new_ver = OSVersion.from_version_string(sys.argv[2])


