#!/usr/bin/env python

# post_update
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

from kano_updater.utils import install
from kano_updater.update import Update

update = Update("post")

if update.from_to('Kanux-Beta-1.0', 'Kanux-Beta-1.0.1'):
    install('kano-extras')
elif update.from_to('Kanux-Beta-1.0.1', 'Kanux-Beta-1.0.2'):
    install('gnome-paint')
