#!/usr/bin/env python
# pre_update
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

from kano_updater.Utils import install, remove, purge
from kano_updater.Update import Update

update = Update("pre")

if update.from_to('Kanux-Beta-1.0', 'Kanux-Beta-1.0.1'):
    pass
