bin/* usr/bin

kano_updater usr/lib/python2.7/dist-packages/

lxpanel-plugin/kano_updater.so usr/lib/arm-linux-gnueabihf/lxpanel/plugins/
lxpanel-plugin/images usr/share/kano-updater/

icon/updater.app usr/share/applications/
icon/kano-updater.png usr/share/icons/Kano/66x66/apps/

locale/* /usr/share/locale

conf/apt/preferences etc/apt/
conf/dhcpcd-hooks lib/dhcpcd/
conf/systemd usr/lib/
conf/dist-packages usr/lib/python2.7/
