#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

TMP_FILE=/tmp/kano-updater_conf
OLD_UPDATER_STATUS=/var/cache/kano-updater/status

LXDE_AUTOSTART_PATH="/etc/xdg/lxsession/LXDE/autostart"
UPDATER_CMD="kano-updater ui boot-window"

case "$1" in
    configure)

        # Create custom sudoers file
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/kano-updater" > $TMP_FILE
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/expand-rootfs" >> $TMP_FILE

        # The owner and group for the sudoers file must both be 0
        chown root:root $TMP_FILE

        # The file permissions must be set to 0440
        chmod 0440 $TMP_FILE

        # Move the file to the sudoers directory
        mv $TMP_FILE /etc/sudoers.d/

        # Remove the old status file - if present
        if [ -f "$OLD_UPDATER_STATUS" ]; then
            rm $OLD_UPDATER_STATUS
        fi

        # Add a command to run every time LXDE starts up
        if ! grep "$UPDATER_CMD" "$LXDE_AUTOSTART_PATH"; then
            echo "\n$UPDATER_CMD" >> $LXDE_AUTOSTART_PATH
        fi

        ;;
esac

#DEBHELPER#

exit 0
