#!/bin/bash

# postinst
#
# Copyright (C) 2014-2015 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

TMP_FILE=/tmp/kano-updater_conf
OLD_UPDATER_STATUS=/var/cache/kano-updater/status
KANO_SOURCES="/etc/apt/sources.list.d/kano.list"
URGENT_REPO="
#
# Kano Urgent Repository
# Contains urgent fixes to packages
#
# Key:
# curl -L http://repo.kano.me/archive/repo.gpg.key | apt-key add -
#
deb http://repo.kano.me/archive/ release-urgent main
"

PIP_DEPENDENCIES="docopt ping"

case "$1" in
    configure)

        # Create custom sudoers file
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/kano-updater" > $TMP_FILE
        echo "%sudo   ALL=(root) NOPASSWD: /usr/bin/expand-rootfs" >> $TMP_FILE

        # The owner and group for the sudoers file must both be 0
        chown root:root $TMP_FILE

        # The file permissions must be set to 0440
        chmod 0440 $TMP_FILE

        # Move the file to the sudoers directory
        mv $TMP_FILE /etc/sudoers.d/

        # Remove the old status file - if present
        if [ -f "$OLD_UPDATER_STATUS" ]; then
            rm $OLD_UPDATER_STATUS
        fi

        pip install --upgrade $PIP_DEPENDENCIES

        # Add the urgent repo to sources - if not already existent
        pcregrep -qM "\"$URGENT_REPO\"" $KANO_SOURCES || echo "$URGENT_REPO" >> $KANO_SOURCES

        ;;
esac

#DEBHELPER#

exit 0
